export const ALL_MESSAGES_REQUEST = 'ALL_MESSAGES_REQUEST';
export const ALL_MESSAGES_SUCCESS = 'ALL_MESSAGES_SUCCESS';
export const ALL_MESSAGES_FAIL = 'ALL_MESSAGES_FAIL';

export const NEW_MESSAGE_REQUEST = 'NEW_MESSAGE_REQUEST';
export const NEW_MESSAGE_SUCCESS = 'NEW_MESSAGE_SUCCESS';
export const NEW_MESSAGE_FAIL = 'NEW_MESSAGE_FAIL';

export const UPDATE_MESSAGE_REQUEST = 'UPDATE_MESSAGE_REQUEST';
export const UPDATE_MESSAGE_SUCCESS = 'UPDATE_MESSAGE_SUCCESS';
export const UPDATE_MESSAGE_FAIL = 'UPDATE_MESSAGE_FAIL';
export const UPDATE_MESSAGE_RESET = 'UPDATE_MESSAGE_RESET';

export const DELETE_MESSAGE_REQUEST = 'DELETE_MESSAGE_REQUEST';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_FAIL';
export const DELETE_MESSAGE_RESET = 'DELETE_MESSAGE_RESET';

export const MESSAGE_DETAILS_REQUEST = 'MESSAGE_DETAILS_REQUEST';
export const MESSAGE_DETAILS_SUCCESS = 'MESSAGE_DETAILS_SUCCESS';
export const MESSAGE_DETAILS_FAIL = 'MESSAGE_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
