export const ALL_PRODUCTS_REQUEST = 'ALL_PRODUCTS_REQUEST';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'ALL_PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'ALL_PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'ALL_PRODUCT_DETAILS_FAIL';

export const PRODUCT_SEARCH_REQUEST = 'ALL_PRODUCT_SEARCH_REQUEST';
export const PRODUCT_SEARCH_SUCCESS = 'ALL_PRODUCT_SEARCH_SUCCESS';
export const PRODUCT_SEARCH_FAIL = 'ALL_PRODUCT_SEARCH_FAIL';

export const ADMIN_PRODUCTS_REQUEST = 'ADMIN_PRODUCTS_REQUEST';
export const ADMIN_PRODUCTS_SUCCESS = 'ADMIN_PRODUCTS_SUCCESS';
export const ADMIN_PRODUCTS_FAIL = 'ADMIN_PRODUCTS_FAIL';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCTS_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCTS_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCTS_FAIL';
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCTS_RESET';

export const NEW_PRODUCT_REQUEST = 'NEW_PRODUCTS_REQUEST';
export const NEW_PRODUCT_SUCCESS = 'NEW_PRODUCTS_SUCCESS';
export const NEW_PRODUCT_FAIL = 'NEW_PRODUCTS_FAIL';
export const NEW_PRODUCT_RESET = 'NEW_PRODUCTS_RESET';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCTS_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCTS_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCTS_FAIL';
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCTS_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
